// Authentication check
function checkAuth() {
    const token = localStorage.getItem('authToken');
    const isLoggedIn = sessionStorage.getItem('isLoggedIn');
    
    if (!token || !isLoggedIn) {
        window.location.href = 'login.html';
        return false;
    }
    return true;
}

// Initialize page
function initReports() {
    if (!checkAuth()) return;
    
    // Get user data
    const username = sessionStorage.getItem('username') || localStorage.getItem('rememberedUser') || 'User';
    const role = localStorage.getItem('userRole') || 'employee';
    
    // Display name (use saved full name if available, otherwise use username)
    const savedFullName = localStorage.getItem('userFullName');
    let displayName;
    if (savedFullName) {
        displayName = savedFullName;
    } else {
        displayName = username.split('@')[0];
        displayName = displayName.charAt(0).toUpperCase() + displayName.slice(1);
    }
    document.getElementById('usernameDisplay').textContent = displayName;
    
    // Show admin elements if user is admin
    if (role === 'admin') {
        document.querySelectorAll('.admin-only').forEach(el => {
            el.style.display = 'block';
        });
    }
}

// Generate Report
async function generateReport(reportType) {
    console.log('Generating report:', reportType);
    
    const reportName = reportType.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    
    try {
        // Initialize jsPDF
        const { jsPDF } = window.jspdf;
        const doc = new jsPDF();
        
        // Company branding colors
        const primaryBlue = [59, 130, 246];
        const darkText = [26, 35, 50];
        const lightGray = [107, 114, 128];
        
        // Add header with company name
        doc.setFillColor(...primaryBlue);
        doc.rect(0, 0, 210, 40, 'F');
        
        // Company name
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(24);
        doc.setFont(undefined, 'bold');
        doc.text('Herald Business Solutions', 105, 20, { align: 'center' });
        
        doc.setFontSize(12);
        doc.setFont(undefined, 'normal');
        doc.text('Inventory Management System', 105, 30, { align: 'center' });
        
        // Report title
        doc.setTextColor(...darkText);
        doc.setFontSize(18);
        doc.setFont(undefined, 'bold');
        doc.text(reportName + ' Report', 20, 55);
        
        // Report metadata
        doc.setFontSize(10);
        doc.setFont(undefined, 'normal');
        doc.setTextColor(...lightGray);
        const currentDate = new Date().toLocaleDateString('en-US', { 
            year: 'numeric', 
            month: 'long', 
            day: 'numeric' 
        });
        const username = sessionStorage.getItem('username') || 'User';
        doc.text(`Generated: ${currentDate}`, 20, 65);
        doc.text(`Generated by: ${username}`, 20, 70);
        
        // Add line separator
        doc.setDrawColor(...primaryBlue);
        doc.setLineWidth(0.5);
        doc.line(20, 75, 190, 75);
        
        // Report content based on type
        let yPos = 85;
        doc.setTextColor(...darkText);
        doc.setFontSize(11);
        
        switch(reportType) {
            case 'inventory-summary':
                yPos = generateInventorySummary(doc, yPos);
                break;
            case 'low-stock':
                yPos = generateLowStockReport(doc, yPos);
                break;
            case 'category-breakdown':
                yPos = generateCategoryBreakdown(doc, yPos);
                break;
            case 'location':
                yPos = generateLocationReport(doc, yPos);
                break;
            case 'valuation':
                yPos = generateValuationReport(doc, yPos);
                break;
            case 'activity-log':
                yPos = generateActivityLog(doc, yPos);
                break;
        }
        
        // Add footer
        const pageCount = doc.internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(9);
            doc.setTextColor(...lightGray);
            doc.text(`Page ${i} of ${pageCount}`, 105, 285, { align: 'center' });
            doc.text('Herald Business Solutions - Confidential', 105, 290, { align: 'center' });
        }
        
        // Save the PDF
        const fileName = `${reportType}-report-${Date.now()}.pdf`;
        doc.save(fileName);
        
        console.log('Report generated successfully');
    } catch (error) {
        console.error('Error generating report:', error);
        alert('Error generating PDF report. Please try again.');
    }
}

// Report content generators
function generateInventorySummary(doc, yPos) {
    doc.setFont(undefined, 'bold');
    doc.text('Inventory Overview', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    const data = [
        ['Total Items', '87'],
        ['Total Categories', '6'],
        ['Items in Stock', '72'],
        ['Items Checked Out', '12'],
        ['Items Under Maintenance', '3'],
        ['Low Stock Items', '3'],
        ['Total Inventory Value', 'GH\u20B5 45,230.00']
    ];
    
    data.forEach(([label, value]) => {
        doc.text(label + ':', 25, yPos);
        doc.setFont(undefined, 'bold');
        doc.text(value, 100, yPos);
        doc.setFont(undefined, 'normal');
        yPos += 7;
    });
    
    return yPos + 10;
}

function generateLowStockReport(doc, yPos) {
    doc.setFont(undefined, 'bold');
    doc.text('Low Stock Alert Items', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    const items = [
        { name: 'Printer Paper A4', quantity: 2, minStock: 10, category: 'Office Supplies' },
        { name: 'Toner Cartridge HP', quantity: 1, minStock: 5, category: 'Electronics' },
        { name: 'USB Flash Drives', quantity: 3, minStock: 10, category: 'Electronics' }
    ];
    
    items.forEach((item, index) => {
        doc.setFont(undefined, 'bold');
        doc.text(`${index + 1}. ${item.name}`, 25, yPos);
        yPos += 6;
        doc.setFont(undefined, 'normal');
        doc.text(`   Category: ${item.category}`, 25, yPos);
        yPos += 5;
        doc.text(`   Current Stock: ${item.quantity} | Minimum Required: ${item.minStock}`, 25, yPos);
        yPos += 10;
    });
    
    return yPos;
}

function generateCategoryBreakdown(doc, yPos) {
    doc.setFont(undefined, 'bold');
    doc.text('Items by Category', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    const categories = [
        { name: 'Office Supplies', count: 32, value: 'GH₵ 8,450' },
        { name: 'Electronics', count: 28, value: 'GH₵ 25,300' },
        { name: 'Furniture', count: 15, value: 'GH₵ 9,200' },
        { name: 'Equipment', count: 8, value: 'GH₵ 1,850' },
        { name: 'Stationery', count: 4, value: 'GH₵ 430' }
    ];
    
    categories.forEach((cat) => {
        doc.text(cat.name, 25, yPos);
        doc.text(`${cat.count} items`, 100, yPos);
        doc.text(cat.value, 150, yPos);
        yPos += 7;
    });
    
    return yPos + 10;
}

function generateLocationReport(doc, yPos) {
    doc.setFont(undefined, 'bold');
    doc.text('Items by Location', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    const locations = [
        { name: 'Main Office', items: 45 },
        { name: 'Storage Room A', items: 23 },
        { name: 'Conference Room', items: 12 },
        { name: 'IT Department', items: 7 }
    ];
    
    locations.forEach((loc) => {
        doc.text(loc.name + ':', 25, yPos);
        doc.setFont(undefined, 'bold');
        doc.text(`${loc.items} items`, 100, yPos);
        doc.setFont(undefined, 'normal');
        yPos += 7;
    });
    
    return yPos + 10;
}

function generateValuationReport(doc, yPos) {
    doc.setFont(undefined, 'bold');
    doc.text('Inventory Valuation', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    doc.text('Total Asset Value: GH₵ 45,230.00', 25, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'bold');
    doc.text('Value Breakdown:', 25, yPos);
    yPos += 8;
    
    doc.setFont(undefined, 'normal');
    const breakdown = [
        ['Electronics', 'GH₵ 25,300.00', '56%'],
        ['Furniture', 'GH₵ 9,200.00', '20%'],
        ['Office Supplies', 'GH₵ 8,450.00', '19%'],
        ['Equipment', 'GH₵ 1,850.00', '4%'],
        ['Stationery', 'GH₵ 430.00', '1%']
    ];
    
    breakdown.forEach(([category, value, percentage]) => {
        doc.text(category, 30, yPos);
        doc.text(value, 100, yPos);
        doc.text(percentage, 150, yPos);
        yPos += 7;
    });
    
    return yPos + 10;
}

function generateActivityLog(doc, yPos) {
    doc.setFont(undefined, 'bold');
    doc.text('Recent Activity (Last 7 Days)', 20, yPos);
    yPos += 10;
    
    doc.setFont(undefined, 'normal');
    const activities = [
        { date: 'Nov 14', action: 'Added', item: 'Dell Monitor 27"', user: 'John Doe' },
        { date: 'Nov 13', action: 'Updated', item: 'HP Printer', user: 'Jane Smith' },
        { date: 'Nov 13', action: 'Checked Out', item: 'Office Chair', user: 'Kwame Mensah' },
        { date: 'Nov 12', action: 'Returned', item: 'Laptop Lenovo', user: 'Ama Osei' },
        { date: 'Nov 11', action: 'Deleted', item: 'Old Keyboard', user: 'John Doe' }
    ];
    
    activities.forEach((activity) => {
        doc.setFont(undefined, 'bold');
        doc.text(activity.date, 25, yPos);
        doc.setFont(undefined, 'normal');
        doc.text(`${activity.action}: ${activity.item}`, 45, yPos);
        doc.text(`by ${activity.user}`, 140, yPos);
        yPos += 7;
    });
    
    return yPos;
}

// Export Report
function exportReport(reportType) {
    console.log('Exporting report:', reportType);
    
    // Show loading state
    const reportName = reportType.replace(/-/g, ' ').replace(/\b\w/g, l => l.toUpperCase());
    
    // Mock CSV export
    alert(`Exporting ${reportName} Report...\n\nThis would download a CSV file in a real application.\n\nReport Type: ${reportType}\nFormat: CSV\nExported by: ${sessionStorage.getItem('username') || 'User'}\nDate: ${new Date().toLocaleDateString()}`);
    
    // In a real app, this would trigger CSV download
    console.log('Report exported successfully');
}

// Generate Custom Report
function generateCustomReport() {
    const reportType = document.getElementById('customReportType').value;
    const dateRange = document.getElementById('dateRange').value;
    const format = document.getElementById('reportFormat').value;
    
    console.log('Generating custom report:', { reportType, dateRange, format });
    
    // Mock custom report generation
    alert(`Generating Custom Report...\n\nReport Type: ${reportType}\nDate Range: ${dateRange}\nFormat: ${format.toUpperCase()}\nGenerated by: ${sessionStorage.getItem('username') || 'User'}\nDate: ${new Date().toLocaleDateString()}\n\nThis would generate and download the custom report in a real application.`);
    
    console.log('Custom report generated successfully');
}

// Sidebar navigation
const sidebar = document.getElementById('sidebar');
const closeSidebar = document.getElementById('closeSidebar');

closeSidebar.addEventListener('click', () => {
    sidebar.classList.remove('active');
});

document.querySelectorAll('.nav-link').forEach(link => {
    link.addEventListener('click', () => {
        if (window.innerWidth <= 1024) {
            sidebar.classList.remove('active');
        }
    });
});

// Logout
const logoutModal = document.getElementById('logoutModal');
const logoutBtn = document.getElementById('logoutBtn');
const cancelLogout = document.getElementById('cancelLogout');
const confirmLogout = document.getElementById('confirmLogout');

logoutBtn.addEventListener('click', (e) => {
    e.preventDefault();
    logoutModal.classList.add('active');
});

cancelLogout.addEventListener('click', () => {
    logoutModal.classList.remove('active');
});

confirmLogout.addEventListener('click', () => {
    localStorage.removeItem('authToken');
    sessionStorage.removeItem('isLoggedIn');
    sessionStorage.removeItem('username');
    window.location.href = 'login.html';
});

logoutModal.addEventListener('click', (e) => {
    if (e.target === logoutModal) {
        logoutModal.classList.remove('active');
    }
});

// Top nav scroll effect
const topNav = document.querySelector('.top-nav');
window.addEventListener('scroll', () => {
    if (window.scrollY > 10) {
        topNav.classList.add('scrolled');
    } else {
        topNav.classList.remove('scrolled');
    }
});

// Placeholder function
function showPlaceholder(page) {
    console.log(`Navigating to: ${page}`);
    alert(`${page} page is under development. This is a placeholder.`);
}

// Initialize on page load
window.addEventListener('DOMContentLoaded', initReports);